language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 8.0
  - 8.1snapshot

matrix:
  include:
  - php: 8.0
    env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
  - php: 8.1snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
